POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "abaig",
  "password": "hello"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "abaig",
  "password": "hel"
}