###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "abaig",
  "name": "Ali Baig",
  "password": "hello"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "a",
  "name": "Ali Baig",
  "password": "h"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "aasdfe",
  "name": "Ali Baig",
  "password": "h"
}